#!/usr/bin/python3 -I
import pwd
import os
import runpy
from pathlib import Path
runpy.run_path(str(Path(pwd.getpwuid(os.getuid()).pw_dir) / '.local/share/legion-super-key-rgb/entry.py'), run_name='__main__')
