name: Tests
on: [push, pull_request]
permissions:
  contents: read
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: /usr/bin/python3 -I tests/test_helper.py
      - run: /usr/bin/python3 -I tests/test_install.py
      - run: /usr/bin/python3 -I tests/test_safety.py
      - run: /usr/bin/python3 -I -m py_compile src/helper.py src/spectrum.py src/safety.py src/entry.py install.py
